### ISSUE TITLE
SR-17-0000375: TiPSS Project

### ISSUE THREAD

**Issue by JaneSchneider-COM** [City-of-Madison/Development-Team-2#11]
Integrate ERP with TiPSS regarding online payments
F:\Information Technology\Applications and Systems\ERPMiddleware\Active Project\SR-17-0000375 Integrate ERP with TiPSS\Meeting Notes

**Comment by JaneSchneider-COM** [comment]
**Tasks**
- [ ] Create new Bizcash database tables in Dev
     - [ ] Create CourtHeader table
     - [ ] Create CourtDetail table
     - [ ] Create CourtPaymentWCF table

**Comment by RikiSjachrani-COM** [comment]
@JaneSchneider-COM If you move the to do list to the first comment, it will show from the issues screen the open and completed tasks

**Comment by RikiSjachrani-COM** [comment]
I've included Chris on this project as well, with the intention that he can get more familiar with SRs related to middleware.

**Comment by KimGrittner-COM** [comment]
The XML and XSD samples can be found here:
F:\Information Technology\Applications and Systems\ERPMiddleware\Active Project\SR-17-0000375 Integrate ERP with TiPSS\CitationPayments.xml
F:\Information Technology\Applications and Systems\ERPMiddleware\Active Project\SR-17-0000375 Integrate ERP with TiPSS\CitationPayments.xsd

**Comment by KimGrittner-COM** [comment]
Data Mapping Document located here:
F:\Information Technology\Applications and Systems\ERPMiddleware\Specifications\ERP Cashiering Middleware\Municipal Courts\MuniCourtSpecifications2017.xlsx

**Comment by RikiSjachrani-COM** [comment]
https://webapp/epayment/municipalCourt/form.cfm 
I think this is the test epayment muni court site

**Comment by RikiSjachrani-COM** [comment]
Hey, @KimGrittner-COM @JaneSchneider-COM @ChrisBilik-COM where are we at with this project. I'm thinking of allocating time for the Cashiering portion of the project in Feb and wondering if the other parts of this project is progressing.

**Comment by JaneSchneider-COM** [comment]
@RikiSjachrani-COM @KimGrittner-COM @ChrisBilik-COM: Pretty much done in Dev...I think we just need to do TR Web test in Dev environment to make sure both import and export are working. 
Then we can finish moving everything to Test environment (about 50-60% done).
