### ISSUE TITLE
Civil Rights - Managing Service Request Changes and Issues

### ISSUE THREAD

**Issue by RikiSjachrani-COM** [City-of-Madison/Development-Team-2#15]
CR - Have a better handle on Civil Rights issues and changes with AA Plans

It is difficult to keep track of changes and issues, be on the same page on changes and where things are at, better coordination with IT and CR staff

To accomplish this - Have a shared document that has a list of changes, issues, their status. Any new issues can be put into Git Hub prior to bein added to the shared document

We will know we are making progress when we can easily add to and update ongoing shared list, this is also used to communicate to CR and know this is completed when this becomes a routine and the number of changes and issues get turned around in a reasonable amount of time

This should be completed by the end of first quarter of 2018 and we should be halfway done with we have completed half of the changes and issues

Resource wise, try to allocate - Jackie will be the main developer and contact for CR, and we will bring in Chris for scripting and Brenden for reporting

Next Actionable Steps:
- [ ] Create Shared Change/Issues document
- [ ] Update with relevant information (SR, Status, Last Update Date, etc...)
- [ ] Create re-occuring meetings to discuss progress
- [ ] List of changes
- [ ] …

After a SR is complete we provide some document to CR with agreed step of what action to take when the particular issue occurs

**Comment by JacquelineGoltz-COM** [comment]
I created service requests for all outstanding issues and assigned them to me.  We can now run a report.

**Comment by RikiSjachrani-COM** [comment]
Jackie, there's a request from Felicia for WAGs data for the Mayor, I'm going to start to develop a adhoc view for this

**Comment by ChrisHagen-COM** [comment]
@RikiSjachrani-COM I'm just ploughing through the fire dept acct setup at the moment.

**Comment by RikiSjachrani-COM** [comment]
Ok, I'm meeting with Brenden and then hopefully you can work on this
