### ISSUE TITLE
Accela Version 9 Upgrade

### ISSUE THREAD

**Issue by RikiSjachrani-COM** [City-of-Madison/Development-Team-2#4]
To Do or noted in a meeting

- [ ] Check SSRS with Version 9
- [ ] Check Communication Manager with newer version of Exchange and see if we can pull in emails
- [ ] Accela Mobile Office check if the deleting of old data profile resolves the issue with unhandled exceptions with Windows 10

**Comment by RikiSjachrani-COM** [comment]
@PaulOLeary-COM I just realized the error I was getting was specific to windows 10 creators edition and AMO version 9, so it is very possible you did not get the error messages when you tried

**Comment by PaulOLeary-COM** [comment]
**1.  Database Migration to SQL Server 2014 (not including SSRS)**
Backup/Restore DBs (Paul):
•	AccelaStage
•	AccelaGISTest
•	AMOTest
•	DaneCountyAPO
•	ELAMSDE
•	jetspeedTest
•	Madison
•	MadisonAccela
•	MadisonAPO ?
•	MadMaps ?
•	Sde_Edit
•	WaterSDE
 
Update DataSources, connection strings, etc (Paul/Riki/Team) - ELAMSQL1\TESTDEV becomes ELAMDBTEST:
•	Biz/CFMX/Web config files (Paul)
•	SSRS Data Sources (Paul/Riki)
•	Crystal conn strings on Crystal servers (Paul/Riki)
•	ODBC connection strings on Team workstations (Team members)
•	Where else?....
 
**2.  Update Accela to 9.1.2 (Paul)**
•	Civic Platform
•	ACA
•	AMO
•	AGIS
•	Ad Hoc? - May not be separate install
 
**3a.  New GIS Layers (Aaron/Paul)**
•	Update GIS database with new layers/groups (Aaron)
•	Setup new GIS / Accela Integration (Aaron/Paul)
 
**3b.  Migrate SSRS to SQL 2014 (Paul)**
•	Copy custom SSRS config items from Dev
•	Set up MSSQL2014 Service in Report Manager
•	Test 1-3 reports
•	Run Report migration tool (ReportSync)
•	Run SQL update to point all MSSQL2008 reports to MSSQL2014
•	Shut down MSSQL2008 Report Service

**Comment by PaulOLeary-COM** [comment]
@RikiSjachrani-COM - With no objections, I'm going to migrate the databases to the 2014 instance (alias name ELAMDBTEST) tonight. Take a look at my list above of DataSources, connection strings, etc. Do you know of any I'm missing? I'll inform the team this afternoon that they need to update their own ODBCs, and can assist them tomorrow as needed.

**Comment by RikiSjachrani-COM** [comment]
What about updating the index service? Is that something that could be included in 2? Also, just brainstorming here but there are a couple of things we needed to do after upgrades or hotfixes. Like
- [ ] After AMO upgrade, delete extra reports from default profile
- [ ] After ACA upgrade, reload the custom deep link file
- [ ] After the Adhoc Report, reconfigure the Record ID to https so that the hotlink resolves

Those are what I though of...I'll add more as I think of them

**Comment by RikiSjachrani-COM** [comment]
@PaulOLeary-COM I am getting a database error when opening Adhoc reports in Test, when you have time could you look into this?
![image](https://user-images.githubusercontent.com/13784495/29426625-d6cfbcfc-834c-11e7-809b-953b0540da49.png)
- [ ] Fix adhoc report database error

**Comment by PaulOLeary-COM** [comment]
Try it now. You'll have to close Ad Hoc window and follow the link again.

**Comment by PaulOLeary-COM** [comment]
# Options/Questions for LIVE upgrade - For Thurs PM meeting

- Uninstall / reinstall, or in-place?
-- Reinstall on any IIS components - install to D:\Accela\wwwroot if possible, to keep off C: drive
-- Any shares on existing folders? If new created, we'll need to re-create
- GIS / settings
-- JS - Should find existing data (DB)
-- SL - Rebuild, or use MADISON folder? - Update AGENCIES.XML file
- Certificates
-- JBoss (AA/AV) - May need to re-run create-certs command scripts
-- IIS (ELAM.) - Bind via IIS Manager

**Comment by PaulOLeary-COM** [comment]
# Checklist for LIVE upgrade

Preliminary checklist....

**1.  Backup DBs (Paul):**
- [ ] AccelaProd
- [ ] AccelaGISProd (JS)
- [ ] AMOTest
- [ ] jetspeed
 
**2.  Upgrade Accela to 9.1.3 **
- [ ] Database updates - ELAMDBPRD
- [ ] Civic Platform - ELAM7APP1, ELAM7APP2, ELAM7WEB, ELAM7INDEX
- [ ] Will need new license key
- [ ] ACA/Kiosk - ELAM7WACA
- [ ] --After ACA upgrade, reload the custom deep link file
- [ ] AMO - ELAM7WACA
- [ ] --After AMO upgrade, delete reports from default profile
- [ ] AGIS, AGISJS - ELAM7GIS
- [ ] Ad Hoc - ELAM7REPORT
- [ ] -- In the install dialogue, don't include https: on the server name, so hot links will work correctly
- [ ] After ALL IIS installs, turn OFF HTTP redirect except at the root!
 
**3. Other Post-upgrade**
- [ ] Certificate - IIS (ELAM7WACA server)
- [ ] Cert - JBOSS servers
- [ ] GIS......

**Comment by PaulOLeary-COM** [comment]
@RikiSjachrani-COM , AMO client question/concern - when AMO users get the invite to download the upgrade, will AppLocker get in the way?

If I recall, for new AMO users, we put the install in \\SCCM\Packages, and there's an AppLocker exception for it. Does that sound right? We'll need to do that anyway, so I'll get that ball rolling. But I'm wondering if we should just use that for current users come Monday AM.

Can you think of any potential weekend AMO users? Health inspectors doing temp foods at any weekend events, maybe?

**Comment by RikiSjachrani-COM** [comment]
@PaulOLeary-COM I don't believe we will run into any issues with weekend users, and I think I will inquire with the help desk about the app blocker scenario. It would seem like it would be blocked, but wouldn't we have run into this in the past?

**Comment by PaulOLeary-COM** [comment]
I have another question for Molly, so I'll inquire about this as well. Meanwhile, I'm going to try downgrading my desktop machine to AMO 8.xxx, then login as that test non-IT user and see what happens when it tries to upgrade via the AMO download. Just so we know what to expect on Monday.

**Comment by PaulOLeary-COM** [comment]
I think we'll be okay with updating existing AMO users upgrading. I logged in with the TESTSW (non-IT) AD user, and the AMO download upgraded the client to 9.1.3 with no problem.

For new user installs in the future, I put the 9.1.3 client install files (choice of EXE or MSI) in \\SCCM\Packages, and entered a HEAT request to add AppLocker exceptions for them.

**Comment by RikiSjachrani-COM** [comment]
I will do the same on the surface tablet I use and downgrade to AMO 8.x

**Comment by PaulOLeary-COM** [comment]
Shoot, this time it failed.

![amoupderr](https://user-images.githubusercontent.com/19735470/31029410-32ffc120-a517-11e7-80b2-ae869e3abbc3.JPG)

But Event Viewer -> AppLocker doesn't show any entries for "was not allowed to run". 

Maybe we should just instruct people to run the exe from \\sccm\packages .

**Comment by PaulOLeary-COM** [comment]
Update - as I mentioned in my voice mail, the AMO update-via-download failed in the Test OU. But nothing in the AppLocker Event Viewer indicating anything not allowed to run.

On a hunch, well, knowing that the SERVER service is disabled for many/most OUs, I enabled the SERVER service, and started it. Then tried the AMO update-via-download again, and this time it worked.

Soooo.... question is - for Health, BI, Engineering staff, based on the containers (?) their workstations are in, would they have the Server service enabled/started? I know we do that for some other containers, like Parks (for RecTrac). Molly, can you sleuth that out?

Thanks,
Paul

From: Larson, Molly
Sent: Friday, 29 September 2017 12:42
To: Oleary, Paul <POLeary@cityofmadison.com>
Subject: Test OU

Hi Paul,

I moved your PC (ITDT-5467V12) into the Test OUs > Test Workstation, so give it a reboot when you have a chance. Once it reboots, it should pull the new group policy and apply the Applocker settings to test with that testsw account.
Thanks!

Molly Larson
City of Madison
Information Technology
(608) 266-4193

**Comment by PaulOLeary-COM** [comment]
Well, it definitely isn’t needed for the software to run, or we would have had issues a long time ago with the existing version.

Buuuuut…. another update. I tried it again, with the WS in the Env Health container, and it worked. This is with Server service disabled and NOT running. So I THINK we’re good to go with the in-place upgrade. 

For the time being, can you keep my desktop WS in that Health container? Push comes to shove, I've got my laptop and the Dell tablet, to work as "me".

@RikiSjachrani-COM , so maybe it wasn't the Server service. Hard to say what **did** make it work. Maybe it just takes two tries <shrug> . I'm thinking, instead of complicating the final notice with instructions about the \\\sccm install, we should just go ahead with the Download option. We MIGHT even want to mention that if it fails, try it a second time before calling us.

Speaking of which, I did one more re-enactment, installed the 8.0 client, then, rather than the Download, I ran the EXE from \\\SCCM\Packages. Just in case we need it come Monday. It ran, and upgraded, but:
- Both versions show up in Programs and Features. Probably a non-issue, since it's all in the same Program Files folder
- It at least wiped out the connection info, for user group (MADISON, MADISON_TEST, etc) and server URLs. I don't really have any way of knowing if it wipes out local data. 

------------------------------------------------------------------------
From: Larson, Molly 
Sent: Friday, 29 September 2017 14:27
To: Oleary, Paul <POLeary@cityofmadison.com>
Cc: IT Dev Team 2 <ITDevTeam2@cityofmadison.com>
Subject: RE: Test OU

Hi Paul,

There is a GPO to disable/stop the SERVER service from running on all workstations unless they are exempt for whatever reason. Does that service only need to be enabled for installing the software? Or is it also needed for the software to run? 

Molly

**Comment by RikiSjachrani-COM** [comment]
@PaulOLeary-COM ok, thats good. I am going to expect a fair amount of manual intervention with AMO. I'm just skeptical it's going to work for most of the people.

**Comment by PaulOLeary-COM** [comment]
Ye of little faith.... 

Status @ 17:40
Backup is done. DB Updates are done.
APP2 BIZ is uninstalled, new install going now - so far it's remembering settings from saved copy properly
WACA - uninstalled KIOSK, reinstalling - requires Dot Net 4.6, ELAM7WACA server restarting after 4.6 install

**Comment by RikiSjachrani-COM** [comment]
I see the license key file you mention but it's the same as the current key being used by 8.x...I'm going to give it a whirl. If not, I'll check out our CRC cases

![image](https://user-images.githubusercontent.com/13784495/31039651-dcc49ed8-a544-11e7-92dc-57fa5adf441c.png)

**Comment by RikiSjachrani-COM** [comment]
I am getting the following error trying to access adhoc, I'm going to troubleshoot

![image](https://user-images.githubusercontent.com/13784495/31039955-afb978e8-a547-11e7-89c1-11b1fc11be92.png)

**Comment by RikiSjachrani-COM** [comment]
Ok, so it's working now and I'm just trying to run a report to test the hotlink thing

**Comment by PaulOLeary-COM** [comment]
Status @ 21:15
Working
- Civic Platform
- ACA, including deep link
- AMO - one more download/upgrade test, worked
- AGIS (old UI SL)

Issues
- Ad hoc Reporting - working, but throwing a Certificate error, will continue to troubleshoot
- AMO - **If** we have to use the \\\SCCM\Packages install, turns out (oopsie...) the install files I copied there _are_ the 32-bit versions. I copied the 64-bit files up, and will enter a new HEAT request to create AppLocker exceptions for those as well ASAP. In case that's delayed, **may** have a workaround. I deleted the 32-bit files I copied previously, copied the 64-bit files up again, and renamed them to be the same as the 32-bit versions. Since Applocker is based on UNC file string, that SHOULD work.
- Kiosk - I think I need to copy more files from the backup folder. LOW priority......

Remaining - JS AGIS

**Comment by RikiSjachrani-COM** [comment]
@PaulOLeary-COM nice job getting everything sorted out. I'm going through some testing and will list what I've check and note anything to look into Monday. My comments in order of...

Adhoc Certificate error - this started up after the most recent upgrade and I think we just manually installed the cert on user's machines that use adhoc. I don't think this is a new issue

AMO - I think the rename is fine for now and hope that the auto-download works. 

JS AGIS - I'm not too familiar with this install so I'll defer to your knowledge on it

The Kiosk is at the bottom of priorities since it's not being used in production at this point.

**Comment by RikiSjachrani-COM** [comment]
- [x] Checking the elam redirect by going to https://elam.cityofmadison.com/
- [x] Login to Civic Platform
- [x] Login to ACA
- [ ] Civic Platform seems a bit slow but it could be my internet
- [x] The auto assign inspections worked for BLDPLM-2017-14869, this means the GIS SL and Parcel location is working
- [x] Attached documents showing up through civic platform
- [ ] New ACA records since the upgrade
- [ ] Getting a GIS error through ACA 
![image](https://user-images.githubusercontent.com/13784495/31048525-5c2e7bd6-a5e4-11e7-8dcf-0c2eabb61670.png)
- [x] Able to view attached documents through ACA

**Comment by PaulOLeary-COM** [comment]
Ad Hoc Cert error is actually because the Cert expired, not related to the previous service pack. We'll need to regroup on how to handle IIS internal certs.

ACA/GIS - I didn't realize that the GIS installation on WACA was still serving ACA. I thought it was an old remnant. So it's not updated. I can run the upgrade just to make the error go away, but we should review this; maintaining two (well, four with JS+SL) complete AGIS installations is not ideal.

**Comment by PaulOLeary-COM** [comment]
ACA/GIS - Near as I can tell, we need Javascript GIS for ACA. GIS has not worked on ACA in Dev or Test since we upgraded them. I installed AGIS-JS on Dev, but haven't found a way for it to render the map properly. It shows the whole world. I'm thinking it's a user group issue; working on that presently.

**Comment by RikiSjachrani-COM** [comment]
I haven't gotten any calls and there haven't been any heat tickets either...it's almost too quiet
